### ISSUE TITLE
header issues with blend_eeps

### ISSUE THREAD

**Issue by jieunchoi** [aarondotter/iso#3]
using the latest version of the iso code, blend_eeps writes out new .eep files with incomplete header information.

**Comment by aarondotter** [comment]
fixed in commit 6600530b62ae8af650807f42653e7a8a1103b861

**Comment by jieunchoi** [comment]
i'm still seeing the same issue (made sure to make clean and make again, etc.), could you please double check?

**Comment by aarondotter** [comment]
Ok, can you explain what's missing?  When I looked at it today, I saw only
that the star type was "unknown"

**Comment by jieunchoi** [comment]
sorry, that was really ambiguous on my part. i really meant the column headers. i've attached an example here:

<img width="1440" alt="screen shot 2016-01-14 at 10 17 06" src="https://cloud.githubusercontent.com/assets/4583333/12328163/21472d98-baa8-11e5-87eb-e7ee3d70942d.png">

**Comment by aarondotter** [comment]
really(!) fixed in commit f164144e7917d7f6f7744026281ff924ac7d8ed6

**Comment by aarondotter** [comment]
FYI: I found out why this was happening, should be fixed now but check to
make sure!

**Comment by jieunchoi** [comment]
fabulous! it's been fixed :+1: 
thanks!
